### ISSUE TITLE
Work with differet url-pattern

### ISSUE THREAD

**Issue by solokingjec** [adminfaces/admin-showcase#18]
I have added this line on my web.xml 
<servlet-mapping>
        <servlet-name>Faces Servlet</servlet-name>
        <url-pattern>*.htm</url-pattern>
    </servlet-mapping><servlet-mapping>
        <servlet-name>Faces Servlet</servlet-name>
        <url-pattern>*.htm</url-pattern>
    </servlet-mapping> 
That means that my pages are loaded with the extension .htm and not .xhtml. I was trying to show 404 error but it wont show it with .xhtml properly. check this two images.
![screenshot from 2018-02-22 22-47-33](https://user-images.githubusercontent.com/6312641/36560681-80393d08-1822-11e8-9e37-781a3c81a9e8.png)
![screenshot from 2018-02-22 22-46-59](https://user-images.githubusercontent.com/6312641/36560683-8088db38-1822-11e8-9ad3-309451893f92.png)

**Comment by rmpestano** [comment]
Hi, 

you need to override error pages configuration on **web.xml**, as [described here](http://admin-showcase-admin-showcase.7e14.starter-us-west-2.openshiftapps.com/showcase/docs/index.html#providing_custom_error_pages).

For your case it should be:

```
  <error-page>
        <error-code>403</error-code>
        <location>/403.htm</location>
    </error-page>
    <error-page>
        <exception-type>com.github.adminfaces.template.exception.AccessDeniedException</exception-type>
        <location>/403.htm</location>
    </error-page>
    <error-page>
        <error-code>404</error-code>
        <location>/404.htm</location>
    </error-page>
    <error-page>
        <error-code>500</error-code>
        <location>/500.htm</location>
    </error-page>
    <error-page>
        <exception-type>java.lang.Throwable</exception-type>
        <location>/500.htm</location>
    </error-page>
    <error-page>
        <exception-type>javax.faces.application.ViewExpiredException</exception-type>
        <location>/expired.htm</location>
    </error-page>
    <error-page>
        <exception-type>javax.persistence.OptimisticLockException</exception-type>
        <location>/optimistic.htm</location>
    </error-page>
```

You'll also need to change **loginPage** and **indexPage**  configuration in admin-config to respect the desired suffix, [see here](http://admin-showcase-admin-showcase.7e14.starter-us-west-2.openshiftapps.com/showcase/docs/index.html#configuration)

I hope it helps.

**Comment by solokingjec** [comment]
Do i need to add for an example 404.xhtml file in my webpages folder?

**Comment by rmpestano** [comment]
No, only if you want to customize it.
