### ISSUE TITLE
Responsive is not working properly when minimize and maximize the screen

### ISSUE THREAD

**Issue by vishnuragava** [adminfaces/admin-showcase#25]
![admin faces issue](https://user-images.githubusercontent.com/25576826/45210335-ec194c00-b2ac-11e8-88c0-af88600484da.png)

**Comment by rmpestano** [comment]
Hi @vishnuragava,

I  need more details on how to reproduce because it is working for me, see here: https://youtu.be/LhWLAggA61Y

**Comment by vishnuragava** [comment]
Thank you for your response.
https://www.dropbox.com/s/hsbv78pw5h02we4/Admin%20faces%20responsive%20issue.mp4?dl=0
https://www.dropbox.com/s/zqszr3f8y0z7t3c/Admin%20faces%20responsive%20issues.mp4?dl=0

**Comment by vishnuragava** [comment]
Hi @rmpestano ,
I'm using admin template in my project and I couldn't able to continue further process because it's a major issue for me. So could you please give me the possible solution to fix this issue. 
Thank you.

**Comment by rmpestano** [comment]
This issue was moved to adminfaces/admin-template#128
