### ISSUE TITLE
showcase.war

### ISSUE THREAD

**Issue by YahiaZZ** [adminfaces/admin-showcase#27]
Hi,
Please, is there a possibility to share the war file of showcase, I generate it with maven command, but when I tried to deployed in tomcat 7, it gives me this error: 
`Caused by: java.lang.ClassNotFoundException: javax.faces.application.ViewHandler`

Thanks

**Comment by rmpestano** [comment]
Hi, admin-showcase is configured for javaee app servers like glassfish, wildfly or tomme. For Tomcat please use https://github.com/adminfaces/admin-showcase-tomcat

but note that it is not updated as the admin-showcase.

The easiest way to run It is via docker:

```
docker run -it -p 8080:8080 rmpestano/admin-showcase
```
